# This is a basic workflow to help you get started with Actions

name: Auto-add contributors

# Controls when the action will run. 
on:
  schedule:
    - cron:  '20 20 * * *'
  push:
    branches: 
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@v0.0.8
      with:
        REPO_NAME: 'anshulagx/Sentival'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '4'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
